FROM python:3.7.4-alpine3.10
ADD script.py /root/script.py
RUN chmod 0644 /root/script.py

ADD requirements.txt /root/requirements.txt
RUN pip install -r /root/requirements.txt

ADD crontab /etc/cron.d/speedtest-cron
RUN chmod 0644 /etc/cron.d/speedtest-cron
RUN crontab /etc/cron.d/speedtest-cron

ENTRYPOINT [ "crond", "-f" ]